[[plugins]] # toml syntax
on_ft = 'toml'
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
# Lighline
repo = 'itchyny/lightline.vim'

[[plugins]]
# onedark
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme nord
'''
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
# better-whitespace
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
build = './install --all'
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
  nnoremap [gitgutter] <Nop>
  nmap <C-h> [gitgutter]
  nmap [gitgutter]j <Plug>GitGutterNextHunk
  nmap [gitgutter]k <Plug>GitGutterPrevHunk
  nmap [gitgutter]u <Plug>GitGutterUndoHunk
'''
repo = 'airblade/vim-gitgutter'

[[plugins]]
on = 'NERDTreeToggle'
repo = 'xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'maximbaz/lightline-ale'

[[plugins]]
build = 'composer install'
on_ft = ['php']
repo = 'phpactor/phpactor'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
build = './install.sh nightly'
if = '''executable('node') && executable('yarn')'''
merged = '0'
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-surround'

[[pluginsn]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'junegunn/vim-emoji'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
depends = ['context_filetype.vim']
repo = 'osyo-manga/vim-precious'

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'
